version: '2.0'
services:
  db:
    image: mariadb:10.1
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /opt/mediadepot/apps/seafile/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile
  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    volumes:
      - /opt/mediadepot/apps/seafile/seafile:/shared/
      - /media/storage:/data/seafile-fuse:ro
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=db_dev  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=America/Los_Angeles  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=me@example.com # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=asecret     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - 'SEAFILE_SERVER_HOSTNAME=seafile.${DEPOT_DOMAIN_NAME}' # Specifies your host name if https is enabled.
    depends_on:
      - db
      - memcached
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.seafile.loadbalancer.server.port=80"
      - "traefik.http.routers.seafile.rule=Host(`seafile.${DEPOT_DOMAIN_NAME}`)"
      - 'traefik.http.routers.seafile.entrypoints=websecure'
      - 'traefik.http.routers.seafile.tls.certresolver=mydnschallenge'
    networks:
      - seafile
      - traefik
networks:
  traefik:
    external: true
  seafile:
